ausaccessfed/identity-enhancement-service

app/models/subject.rb, spec/models/subject_spec.rb
Users with the same name may come from different institutions.
Closes #26.
=> Subject should not have unique name

app/views/invitations/new.html.erb
Will require rebase after merge of #27
=> Protect invitation creation

app/controllers/api_subject_role_assignments_controller.rb, app/controllers/subject_role_assignments_controller.rb, app/views/api_subject_role_assignments/new.html.erb, app/views/roles/show.html.erb, app/views/subject_role_assignments/new.html.erb, spec/controllers/subject_role_assignments_controller_spec.rb
This PR also cleans ensures only non members are available for addition to roles and cleans up some related UI pieces.
Will require rebase after merge of #29
=> Prevent administrators removing own role membership

app/controllers/dashboard_controller.rb, spec/controllers/dashboard_controller_spec.rb
Will require rebase after merge of #31
=> Dashboard should not show api roles

app/assets/javascripts/application.js, app/assets/stylesheets/application.css.scss, app/helpers/audit_helper.rb, app/views/api_subject_role_assignments/new.html.erb, app/views/api_subjects/index.html.erb, app/views/available_attributes/index.html.erb, app/views/dashboard/index.html.erb, app/views/invitations/index.html.erb, app/views/permissions/index.html.erb, app/views/permitted_attributes/index.html.erb, app/views/provided_attributes/index.html.erb, app/views/provided_attributes/new.html.erb, app/views/providers/index.html.erb, app/views/roles/index.html.erb, app/views/roles/show.html.erb, app/views/subject_role_assignments/new.html.erb, app/views/subjects/index.html.erb
Just some minor UI cleaning
Rebase #34 blah blah
=> minor ui tweaks

app/controllers/invitations_controller.rb, app/views/invitations/new.html.erb, spec/controllers/invitations_controller_spec.rb
Will require rebase after merge of #33
=> Minor invitation issues

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/controllers/permissions_controller.rb, app/models/api_subject.rb, app/models/api_subject_role_assignment.rb, app/models/available_attribute.rb, app/models/invitation.rb, app/models/permission.rb, app/models/permitted_attribute.rb, app/models/provided_attribute.rb, app/models/provider.rb, app/models/role.rb, app/models/subject.rb, app/models/subject_role_assignment.rb, app/views/api_subjects/_form.html.erb, app/views/available_attributes/_form.html.erb, app/views/invitations/new.html.erb, app/views/permissions/index.html.erb, app/views/providers/_form.html.erb, app/views/roles/_form.html.erb, db/migrate/20150316053224_add_unique_index_on_permissions_value.rb, db/migrate/20150316053539_change_roles_provider_id_to_non_nullable.rb, db/schema.rb, spec/controllers/permissions_controller_spec.rb, spec/feature/attributes_admin_spec.rb, spec/feature/providers_admin_spec.rb
* Switch to `valhammer` and remove redundant validations
* Switch to use Lipstick's `auto_validate`
* Added a flash message for permission creation
* Minor tweaks and extra validations
=> Validation improvements

README.md
=> Add links to sample applications in README.md

config/deploy.yml.dist, config/god.rb
This needs to be deployed simultaneously with the corresponding server configuration changes.
=> Change Unicorn to use a TCP socket

app/controllers/invitations_controller.rb, app/views/dashboard/index.html.erb, app/views/invitations/complete.html.erb, config/routes.rb, lib/authentication/subject_receiver.rb, spec/feature/accept_invitation_spec.rb, spec/lib/authentication/subject_receiver_spec.rb, spec/routing/invitations_routing_spec.rb
It's important to feel validated, when you accomplish something as important as accepting an invitation.
Fixes #43
=> Congratulations!

app/controllers/provided_attributes_controller.rb, app/views/invitations/new.html.erb, app/views/provided_attributes/index.html.erb, app/views/provided_attributes/new.html.erb, app/views/provided_attributes/select_subject.html.erb, app/views/providers/show.html.erb, config/routes.rb, spec/controllers/provided_attributes_controller_spec.rb, spec/feature/provided_attributes_spec.rb, spec/feature/provider_invitations_spec.rb, spec/routing/provided_attributes_routing_spec.rb
This was starting to complicate my next pull request, so I've pulled it out into a pull request of its own.
=> Reorganise provided attributes UI

Guardfile, app/assets/javascripts/application.js, app/assets/stylesheets/application.css.scss, app/controllers/concerns/create_invitation.rb, app/controllers/invitations_controller.rb, app/controllers/provided_attributes_controller.rb, app/helpers/application_helper.rb, app/models/invitation.rb, app/models/provider.rb, app/models/subject.rb, app/views/provided_attributes/new.html.erb, app/views/provided_attributes/select_subject.html.erb, bin/remove_expired_data, config/routes.rb, db/migrate/20150326062749_change_invitations_subject_id_to_nullable.rb, db/migrate/20150327042954_add_last_sent_at_to_invitations.rb, db/schema.rb, spec/bin/remove_expired_data_spec.rb, spec/controllers/invitations_controller_spec.rb, spec/controllers/provided_attributes_controller_spec.rb, spec/factories/invitation.rb, spec/factories/subject.rb, spec/feature/provided_attributes_spec.rb, spec/models/invitation_spec.rb, spec/models/subject_spec.rb, spec/routing/invitations_routing_spec.rb, spec/spec_helper.rb
Completes the functionality described in #56 and #61 (except for the piece I pulled out into another ticket)
=> Expired invitation handling

.gitignore, app/assets/stylesheets/application.css.scss, app/controllers/provided_attributes_controller.rb, app/controllers/providers_controller.rb, app/controllers/requested_enhancements_controller.rb, app/models/provider.rb, app/models/requested_enhancement.rb, app/models/subject.rb, app/views/dashboard/index.html.erb, app/views/provided_attributes/new.html.erb, app/views/providers/index.html.erb, app/views/providers/show.html.erb, app/views/requested_enhancements/index.html.erb, app/views/requested_enhancements/new.html.erb, app/views/requested_enhancements/select_provider.html.erb, app/views/requested_enhancements/show.html.erb, config/enhancement_request.md.dist, config/routes.rb, db/migrate/20150417013617_create_requested_enhancements.rb, db/schema.rb, db/seeds.rb, spec/controllers/provided_attributes_controller_spec.rb, spec/controllers/requested_enhancements_controller_spec.rb, spec/factories/requested_enhancement.rb, spec/feature/requested_enhancements_spec.rb, spec/models/provider_spec.rb, spec/models/requested_enhancement_spec.rb, spec/models/subject_spec.rb, spec/routing/requested_enhancements_routing_spec.rb
I'm not 100% sold on 6ab7f82 so happy to peel that commit off if it's bad.
=> Allow users to request identity enhancements from providers

Gemfile, Gemfile.lock, app/controllers/api/attributes_controller.rb, app/controllers/provided_attributes_controller.rb, app/controllers/provisioned_subjects_controller.rb, app/controllers/requested_enhancements_controller.rb, app/models/provider.rb, app/models/provisioned_subject.rb, app/models/subject.rb, app/views/provided_attributes/index.html.erb, app/views/provided_attributes/new.html.erb, app/views/provisioned_subjects/edit.html.erb, config/routes.rb, db/migrate/20150422221016_create_provisioned_subjects.rb, spec/controllers/api/attributes_controller_spec.rb, spec/controllers/provisioned_subjects_controller_spec.rb, spec/factories/provisioned_subject.rb, spec/feature/provided_attributes_spec.rb, spec/models/provisioned_subject_spec.rb, spec/routing/provisioned_subjects_routing_spec.rb
=> Allow the provider / subject relationship to expire, cleaning up provided attributes when it occurs

app/controllers/api/attributes_controller.rb, app/controllers/provided_attributes_controller.rb, app/views/provided_attributes/_attribute_visibility.html.erb, app/views/provided_attributes/index.html.erb, app/views/provided_attributes/new.html.erb, db/migrate/20150427054047_add_public_field_to_provided_attributes.rb, db/schema.rb, spec/controllers/api/attributes_controller_spec.rb, spec/controllers/invitations_controller_spec.rb, spec/controllers/provided_attributes_controller_spec.rb, spec/feature/accept_invitation_spec.rb, spec/feature/provided_attributes_spec.rb, spec/feature/requested_enhancements_spec.rb, spec/rails_helper.rb
Provides the UI side of public/private attribute handling
The API changes will come under #82
Also includes an improvement to the speed + behaviour of Capybara tests.
=> Private attributes

app/controllers/providers_controller.rb, app/views/providers/_form.html.erb, spec/controllers/providers_controller_spec.rb, spec/feature/providers_admin_spec.rb
way the UI is structured](http://i.imgur.com/Idj2H.gif)
The new redirect makes more sense.
=> Redirect to providers/show on create/update

app/controllers/api/attributes_controller.rb, app/models/provider.rb, app/views/api/attributes/show.json.jbuilder, config/dev_unicorn.rb, db/migrate/20150429202326_support_private_attributes_in_default_provider_roles.rb, db/schema.rb, doc/api/v1/subjects.md, spec/controllers/api/attributes_controller_spec.rb, spec/models/provider_spec.rb, spec/requests/api/attributes_spec.rb
Breaking change to the attributes API to address #46 and #82
=> Refactor attributes API

app/controllers/api/providers_controller.rb, app/views/api/providers/index.json.jbuilder, config/routes.rb, doc/api/v1/README.md, doc/api/v1/providers.md, spec/controllers/api/providers_controller_spec.rb, spec/requests/api/providers_spec.rb, spec/routing/api_routing_spec.rb
=> Providers listing API

app/controllers/api/attributes_controller.rb, spec/controllers/api/attributes_controller_spec.rb
=> Create subject by shared token

Gemfile.lock
https://gemnasium.com/ausaccessfed/identity-enhancement-service/alerts
=> Update Nokogiri to address security vulnerability

Gemfile.lock
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-7499
=> Update nokogiri to address CVE-2015-7499

config/database.yml
Relies on https://github.com/ausaccessfed/aaf-ansible/pull/427
=> Direct DB endpoint: Use host and port from environmental variables

README.md
Tidying up the README to reflect our intent that it's now for internal use only.
=> Trim README content

config/initializers/session_store.rb
Hi @smangelsdorf 
As discussed in ausaccessfed/certificate-service#34
Cheers,
Vlad
=> Config: secure session cookies only in production
